Add MUMPS and QRMumps to the list of factorizations
JuliaSmoothOptimizers/JuliaSmoothOptimizers.github.io pull request #88
Opened 2022-08-18 02:34 UTC by amontoison

@tmigot

2022-08-18 02:34 UTC, amontoison commented on ecosystems/linear-algebra.md
> +Mumps implements a direct solution method based on the LDL or LU factorization of the input matrix and is suited to solving general symmetric or unsymmetric linear systems.
```suggestion
MUMPS implements a direct solution method based on the LDL or LU factorization of the input matrix and is suited to solving general symmetric or unsymmetric linear systems.
```

2022-08-18 13:30 UTC, dpo requested changes

2022-08-18 13:30 UTC, dpo commented on ecosystems/linear-algebra.md
> +MUMPS implements a direct solution method based on the LDL or LU factorization of the input matrix and is suited to solving general symmetric or unsymmetric linear systems.
```suggestion
MUMPS implements a direct solution method based on the LDL or LU factorization of the input matrix and is suited to solving square symmetric or unsymmetric linear systems.
```

2022-08-18 13:30 UTC, dpo commented on ecosystems/linear-algebra.md
> +Drawbacks of the previous packages are that they are proprietary and/or they can't handle element types except 32 bits and 64 bits native floating point numbers.
I suggest undoing this change. Only the HSL is proprietary. MUMPS and QrMumps are open source.

2022-08-19 05:05 UTC, amontoison commented on ecosystems/linear-algebra.md
> +Two drawbacks of JSL are that it is proprietary and it can't handle element types except 32 bits and 64 bits native floating point numbers.
```suggestion
Two drawbacks of HSL are that it is proprietary and it can't handle element types except 32 bits and 64 bits native floating point numbers.
```

2022-08-19 12:44 UTC, dpo requested changes

2022-08-19 12:44 UTC, dpo commented on ecosystems/linear-algebra.md
> +These software support real and complex, single or double precision arithmetic.
```suggestion
QRMumps and MUMPS support real and complex, single and double precision arithmetic.
```

2022-08-19 12:44 UTC, dpo commented on ecosystems/linear-algebra.md
> +These software support real and complex, single or double precision arithmetic.
all good after that, thanks!

2022-08-19 15:12 UTC, dpo approved these changes
Thank you!

2022-08-19 17:35 UTC, merged